modLoader="javafml"
loaderVersion="[45,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/IronJetpacks/issues"
    modId="ironjetpacks"
    version="${file.jarVersion}"
    displayName="Iron Jetpacks"
    # updateJSONURL="http://myurl.me/"
    displayURL="https://blakesmods.com/iron-jetpacks"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="Tonius, Tomson124"
    description='''
    A fully customizable FE powered jetpacks mod!
    '''

    [[dependencies.ironjetpacks]]
        modId="forge"
        mandatory=true
        versionRange="[45.0.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.ironjetpacks]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.19.4]"
        ordering="NONE"
        side="BOTH"
    [[dependencies.ironjetpacks]]
        modId="cucumber"
        mandatory=true
        versionRange="[6.1.5,)"
        ordering="NONE"
        side="BOTH"