modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
  issueTrackerURL="https://github.com/BlakeBr0/IronJetpacks/issues"
  modId="ironjetpacks"
  version="${file.jarVersion}"
  displayName="Iron Jetpacks"
  # updateJSONURL="http://myurl.me/"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks"
  # logoFile="examplemod.png"
  authors="BlakeBr0"
  credits="Tonius, Tomson124"
  description='''
  A fully customizable FE powered jetpacks mod!
  '''

  [[dependencies.ironjetpacks]]
      modId="forge"
      mandatory=true
      versionRange="[38.0,)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.ironjetpacks]]
      modId="minecraft"
      mandatory=true
      versionRange="[1.18,1.19)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.ironjetpacks]]
      modId="cucumber"
      mandatory=true
      versionRange="[4.1.11,)"
      ordering="NONE"
      side="BOTH"